### ISSUE TITLE
Update README for running `scripts/sample/generate_pointcloud_6d_grasp_poses.py`

### ISSUE THREAD

**Issue by kuldeepbrd1** [TheCamusean/grasp_diffusion#1]
Hi @TheCamusean 

Thanks for sharing the code for this exciting work. I was able to get sample examples to run smoothly. There is a minor issue that might help others save some time.

There is a mismatch in the names of the flag here in the README. There are no flags `n_poses` or `n_obj` in `generate_pointcloud_6d_grasp_poses.py`. 
https://github.com/TheCamusean/grasp_diffusion/blob/f7493dbb60f623e033ebe79852df182986fc00d4/README.md?plain=1#L41

The flags should be updated to `--n_grasps`  and `--obj_id` instead?
```shell
python scripts/sample/generate_pointcloud_6d_grasp_poses.py --n_grasps 10 --obj_id 0
```
---

Also, it might help to clarify in the README, the directory structure imposed by `se3dif/utils/torch_utils.py` and how ACRONYM data and pretrained models should be organized.

Cheers!

**Comment by TheCamusean** [comment]
You are totally right! Thanks alot for bringing these points. I will adapt the README to make it easier to follow. 

We should also add examples on the training. The scripts are there but no info in the README.

Thanks a lot for collaborating on making this better :)

**Comment by TheCamusean** [comment]
README updated.

 Let us know if you find a new problem.
