### ISSUE TITLE
Pre-processing helpers/scripts

### ISSUE THREAD

**Issue by kuldeepbrd1** [TheCamusean/grasp_diffusion#2]
Hi again @TheCamusean 

It's super convenient that you provide pre-processed data to train/demo for the Mugs. The training works smoothly with this training data.
However, I was hoping to test se3dif on other objects. 

Would it be possible for you to upload the pre-processing scripts to generate the pointclouds from object meshes and final grasp annotations?
Or point out how I could go about it after obtaining water-tight meshes using https://github.com/hjwdzh/Manifold ? 

Thanks a lot in advance

**Comment by kuldeepbrd1** [comment]
That's Awesome :)  
Looking forward to it.

**Comment by TheCamusean** [comment]
@kuldeepbrd1 You might find the dataset generation in the dev branch in the scripts folder. 

We will move it to the master branch soon.

**Comment by kuldeepbrd1** [comment]
I see the dev branch. That is already great for me to start playing with it. 

Cheers!
