### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement theseus-ai (from se3dif) (from versions: none) ERROR: No matching distribution found for theseus-ai

### ISSUE THREAD

**Issue by xiaofeiso** [TheCamusean/grasp_diffusion#3]
when I run pip install -e ., I have this problem:
ERROR: 
Could not find a version that satisfies the requirement theseus-ai (from se3dif) (from versions: none) 
ERROR: No matching distribution found for theseus-ai
when i try pip install theseus-ai, output:
ERROR: Could not find a version that satisfies the requirement theseus-ai (from versions: none)
ERROR: No matching distribution found for theseus-ai

my python is 3.7and cuda is 10.2,how to solve this problem?

**Comment by xiaofeiso** [comment]
> > when I run pip install -e ., I have this problem: ERROR: Could not find a version that satisfies the requirement theseus-ai (from se3dif) (from versions: none) ERROR: No matching distribution found for theseus-ai when i try pip install theseus-ai, output: ERROR: Could not find a version that satisfies the requirement theseus-ai (from versions: none) ERROR: No matching distribution found for theseus-ai
> > my python is 3.7and cuda is 10.2,how to solve this problem?
> 
> @xiaofeiso I have a similar environment (Python=3.7 and cuda=10.2) and met a similar issue.
> 
> When I tried `pip install theseus-ai,`, it told me it failed to install `scikit-sparse`, and then I used `conda` instead of `pip`, that is, `conda install -c conda-forge scikit-sparse`. After that, everything's OK.
> 
> So, maybe you can try the same way to fix it.

when i run on ubuntu，this error not occur, theseus-ai look like only ubuntu to run.

**Comment by kuldeepbrd1** [comment]
I am able to install it on py3.7 with cuda 10.2. You might want to check your pip version and upgrade it before installing theseus.
```shell
pip install --upgrade pip
pip install theseus-ai
```

I noticed other issues with latest versions (0.1.1 and 0.1.2) of theseus-ai pre-built wheels on pip, where they collect torch >1.13.0 and cu11 packages from pip disregarding your version of torch/cuda.  I don't think this is a problem for you, but you can still try with one of the older versions (theseus-ai==0.1.0). 

If this doesn't work, the best option would be to build from source as they recommend [here](https://github.com/facebookresearch/theseus/blob/main/README.md#:~:text=We%20currently%20provide%20wheels%20with%20our%20CUDA%20extensions%20compiled%20using%20CUDA%2010.2%20and%20Python%203.9.%20For%20other%20CUDA%20versions%2C%20consider%20installing%20from%20source%20or%20using%20our%20build%20script). 
> `pip install theseus-ai`
> We currently provide wheels with our CUDA extensions compiled using **CUDA 10.2 and Python 3.9**. For other CUDA versions, consider **installing from source or using our [build script]**(https://github.com/facebookresearch/theseus/blob/main/build_scripts/build_wheel.sh).


Hope this helps
Cheers

**Comment by TheCamusean** [comment]
As @kuldeepbrd1 suggested, If you are facing any possible problem with the installation of Theseus, I suggest to install it from the source: https://github.com/AI-App/Theseus

I also added additional information in the ReadMe. Once I have more time, I will modify the requirements file to fix the required packages to a certain version.

Keep me updated if you are having additional problems.
