### ISSUE TITLE
How to reproduce evaluation results from paper on Acronym?

### ISSUE THREAD

**Issue by theophilegervet** [TheCamusean/grasp_diffusion#6]
Hi @TheCamusean,

Thanks for your awesome work!
I'm trying to reproduce results from your paper on Acronym, in particular Fig. 12. in the Appendix evaluating the point cloud conditioned model.

Is there some code in this repo to do this?
If not, how do you recommend doing this?

Thanks,
Theo

**Comment by nifunk** [comment]
Hi @theophilegervet,

we just updated the master branch of the repo and included the grasp evaluation environment in Isaac Sim as well as the calculation of the Earth Mover Distance.

We hope this helps. Otherwise, please let us know.

Best,

Julen and Niklas
